modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "CC-BY-NC-SA-4.0"

[[mods]]
modId = "netherexp"
version = "${version}"
displayName = "Jaden's Nether Expansion"
authors = "ThatJadenXgamer"
description = '''
Reimagines and Expands upon the Entire Nether Dimension
'''
credits = "Bold_Muddy, ceasingbonsai17, Sydokiddo, LudoCrypt, Faithful"
logoFile = "icon.png"

[[dependencies.netherexp]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherexp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherexp]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.netherexp]]
modId="terrablender"
mandatory=true
versionRange="[3.0.1.7,)"
ordering="NONE"